"""
CCH2 Image Checker
==================
Run this script locally to check whether each CCH2 specimen page has an image.
It fetches each page and looks for image-related HTML patterns.

Usage:
    pip install requests
    python check_cch2_images.py

Output: cch2_image_results.csv
"""

import requests
import csv
import time
from concurrent.futures import ThreadPoolExecutor, as_completed

URLS = [
    "https://cch2.org/portal/collections/individual/index.php?occid=1005302",
    "https://cch2.org/portal/collections/individual/index.php?occid=1007750",
    "https://cch2.org/portal/collections/individual/index.php?occid=1012091",
    "https://cch2.org/portal/collections/individual/index.php?occid=1019723",
    "https://cch2.org/portal/collections/individual/index.php?occid=1024091",
    "https://cch2.org/portal/collections/individual/index.php?occid=1038859",
    "https://cch2.org/portal/collections/individual/index.php?occid=1045059",
    "https://cch2.org/portal/collections/individual/index.php?occid=1045591",
    "https://cch2.org/portal/collections/individual/index.php?occid=1045951",
    "https://cch2.org/portal/collections/individual/index.php?occid=1047487",
    "https://cch2.org/portal/collections/individual/index.php?occid=1049270",
    "https://cch2.org/portal/collections/individual/index.php?occid=1049760",
    "https://cch2.org/portal/collections/individual/index.php?occid=1056531",
    "https://cch2.org/portal/collections/individual/index.php?occid=1062233",
    "https://cch2.org/portal/collections/individual/index.php?occid=106233",
    "https://cch2.org/portal/collections/individual/index.php?occid=1064654",
    "https://cch2.org/portal/collections/individual/index.php?occid=106537",
    "https://cch2.org/portal/collections/individual/index.php?occid=1068117",
    "https://cch2.org/portal/collections/individual/index.php?occid=107786",
    "https://cch2.org/portal/collections/individual/index.php?occid=1078648",
    "https://cch2.org/portal/collections/individual/index.php?occid=1079969",
    "https://cch2.org/portal/collections/individual/index.php?occid=1091776",
    "https://cch2.org/portal/collections/individual/index.php?occid=1092827",
    "https://cch2.org/portal/collections/individual/index.php?occid=1092848",
    "https://cch2.org/portal/collections/individual/index.php?occid=110889",
    "https://cch2.org/portal/collections/individual/index.php?occid=1109834",
    "https://cch2.org/portal/collections/individual/index.php?occid=1109866",
    "https://cch2.org/portal/collections/individual/index.php?occid=1113607",
    "https://cch2.org/portal/collections/individual/index.php?occid=1114974",
    "https://cch2.org/portal/collections/individual/index.php?occid=1116413",
    "https://cch2.org/portal/collections/individual/index.php?occid=1123184",
    "https://cch2.org/portal/collections/individual/index.php?occid=1123870",
    "https://cch2.org/portal/collections/individual/index.php?occid=1133685",
    "https://cch2.org/portal/collections/individual/index.php?occid=1135332",
    "https://cch2.org/portal/collections/individual/index.php?occid=1135498",
    "https://cch2.org/portal/collections/individual/index.php?occid=1136130",
    "https://cch2.org/portal/collections/individual/index.php?occid=1142685",
    "https://cch2.org/portal/collections/individual/index.php?occid=1145586",
    "https://cch2.org/portal/collections/individual/index.php?occid=1146969",
    "https://cch2.org/portal/collections/individual/index.php?occid=1147528",
    "https://cch2.org/portal/collections/individual/index.php?occid=1153085",
    "https://cch2.org/portal/collections/individual/index.php?occid=1156433",
    "https://cch2.org/portal/collections/individual/index.php?occid=116271",
    "https://cch2.org/portal/collections/individual/index.php?occid=1166795",
    "https://cch2.org/portal/collections/individual/index.php?occid=1177657",
    "https://cch2.org/portal/collections/individual/index.php?occid=1184063",
    "https://cch2.org/portal/collections/individual/index.php?occid=1192564",
    "https://cch2.org/portal/collections/individual/index.php?occid=1193190",
    "https://cch2.org/portal/collections/individual/index.php?occid=1194214",
    "https://cch2.org/portal/collections/individual/index.php?occid=1201106",
    "https://cch2.org/portal/collections/individual/index.php?occid=1201734",
    "https://cch2.org/portal/collections/individual/index.php?occid=1202206",
    "https://cch2.org/portal/collections/individual/index.php?occid=1208522",
    "https://cch2.org/portal/collections/individual/index.php?occid=1211305",
    "https://cch2.org/portal/collections/individual/index.php?occid=1213435",
    "https://cch2.org/portal/collections/individual/index.php?occid=1219161",
    "https://cch2.org/portal/collections/individual/index.php?occid=1224957",
    "https://cch2.org/portal/collections/individual/index.php?occid=1239382",
    "https://cch2.org/portal/collections/individual/index.php?occid=124275",
    "https://cch2.org/portal/collections/individual/index.php?occid=1249156",
    "https://cch2.org/portal/collections/individual/index.php?occid=128858",
    "https://cch2.org/portal/collections/individual/index.php?occid=130694",
    "https://cch2.org/portal/collections/individual/index.php?occid=132624",
    "https://cch2.org/portal/collections/individual/index.php?occid=141265",
    "https://cch2.org/portal/collections/individual/index.php?occid=147598",
    "https://cch2.org/portal/collections/individual/index.php?occid=150366",
    "https://cch2.org/portal/collections/individual/index.php?occid=1512711",
    "https://cch2.org/portal/collections/individual/index.php?occid=152436",
    "https://cch2.org/portal/collections/individual/index.php?occid=1569504",
    "https://cch2.org/portal/collections/individual/index.php?occid=157452",
    "https://cch2.org/portal/collections/individual/index.php?occid=1591568",
    "https://cch2.org/portal/collections/individual/index.php?occid=1604716",
    "https://cch2.org/portal/collections/individual/index.php?occid=1656222",
    "https://cch2.org/portal/collections/individual/index.php?occid=1668895",
    "https://cch2.org/portal/collections/individual/index.php?occid=18974",
    "https://cch2.org/portal/collections/individual/index.php?occid=1937814",
    "https://cch2.org/portal/collections/individual/index.php?occid=2035482",
    "https://cch2.org/portal/collections/individual/index.php?occid=2035506",
    "https://cch2.org/portal/collections/individual/index.php?occid=2066058",
    "https://cch2.org/portal/collections/individual/index.php?occid=2207182",
    "https://cch2.org/portal/collections/individual/index.php?occid=2207186",
    "https://cch2.org/portal/collections/individual/index.php?occid=2207207",
    "https://cch2.org/portal/collections/individual/index.php?occid=2207216",
    "https://cch2.org/portal/collections/individual/index.php?occid=2207224",
    "https://cch2.org/portal/collections/individual/index.php?occid=2207251",
    "https://cch2.org/portal/collections/individual/index.php?occid=2207273",
    "https://cch2.org/portal/collections/individual/index.php?occid=2207282",
    "https://cch2.org/portal/collections/individual/index.php?occid=2207288",
    "https://cch2.org/portal/collections/individual/index.php?occid=2207308",
    "https://cch2.org/portal/collections/individual/index.php?occid=2207312",
    "https://cch2.org/portal/collections/individual/index.php?occid=2207336",
    "https://cch2.org/portal/collections/individual/index.php?occid=2207339",
    "https://cch2.org/portal/collections/individual/index.php?occid=2207374",
    "https://cch2.org/portal/collections/individual/index.php?occid=2207383",
    "https://cch2.org/portal/collections/individual/index.php?occid=2207423",
    "https://cch2.org/portal/collections/individual/index.php?occid=2207434",
    "https://cch2.org/portal/collections/individual/index.php?occid=2207437",
    "https://cch2.org/portal/collections/individual/index.php?occid=2262520",
    "https://cch2.org/portal/collections/individual/index.php?occid=239858",
    "https://cch2.org/portal/collections/individual/index.php?occid=239881",
    "https://cch2.org/portal/collections/individual/index.php?occid=239908",
    "https://cch2.org/portal/collections/individual/index.php?occid=239971",
    "https://cch2.org/portal/collections/individual/index.php?occid=239984",
    "https://cch2.org/portal/collections/individual/index.php?occid=240008",
    "https://cch2.org/portal/collections/individual/index.php?occid=240030",
    "https://cch2.org/portal/collections/individual/index.php?occid=240045",
    "https://cch2.org/portal/collections/individual/index.php?occid=240048",
    "https://cch2.org/portal/collections/individual/index.php?occid=240097",
    "https://cch2.org/portal/collections/individual/index.php?occid=240127",
    "https://cch2.org/portal/collections/individual/index.php?occid=240160",
    "https://cch2.org/portal/collections/individual/index.php?occid=240188",
    "https://cch2.org/portal/collections/individual/index.php?occid=240208",
    "https://cch2.org/portal/collections/individual/index.php?occid=240217",
    "https://cch2.org/portal/collections/individual/index.php?occid=240225",
    "https://cch2.org/portal/collections/individual/index.php?occid=240237",
    "https://cch2.org/portal/collections/individual/index.php?occid=240241",
    "https://cch2.org/portal/collections/individual/index.php?occid=240297",
    "https://cch2.org/portal/collections/individual/index.php?occid=240327",
    "https://cch2.org/portal/collections/individual/index.php?occid=240360",
    "https://cch2.org/portal/collections/individual/index.php?occid=240388",
    "https://cch2.org/portal/collections/individual/index.php?occid=240408",
    "https://cch2.org/portal/collections/individual/index.php?occid=240417",
    "https://cch2.org/portal/collections/individual/index.php?occid=240425",
    "https://cch2.org/portal/collections/individual/index.php?occid=240437",
    "https://cch2.org/portal/collections/individual/index.php?occid=240441",
    "https://cch2.org/portal/collections/individual/index.php?occid=3042671",
    "https://cch2.org/portal/collections/individual/index.php?occid=3043848",
    "https://cch2.org/portal/collections/individual/index.php?occid=3044356",
    "https://cch2.org/portal/collections/individual/index.php?occid=3113068",
    "https://cch2.org/portal/collections/individual/index.php?occid=3113069",
    "https://cch2.org/portal/collections/individual/index.php?occid=3123760",
    "https://cch2.org/portal/collections/individual/index.php?occid=33390",
    "https://cch2.org/portal/collections/individual/index.php?occid=3590297",
    "https://cch2.org/portal/collections/individual/index.php?occid=3611474",
    "https://cch2.org/portal/collections/individual/index.php?occid=3611826",
    "https://cch2.org/portal/collections/individual/index.php?occid=3611827",
    "https://cch2.org/portal/collections/individual/index.php?occid=3611977",
    "https://cch2.org/portal/collections/individual/index.php?occid=3611979",
    "https://cch2.org/portal/collections/individual/index.php?occid=3611980",
    "https://cch2.org/portal/collections/individual/index.php?occid=3611981",
    "https://cch2.org/portal/collections/individual/index.php?occid=3611982",
    "https://cch2.org/portal/collections/individual/index.php?occid=3611984",
    "https://cch2.org/portal/collections/individual/index.php?occid=3611985",
    "https://cch2.org/portal/collections/individual/index.php?occid=3611986",
    "https://cch2.org/portal/collections/individual/index.php?occid=3611987",
    "https://cch2.org/portal/collections/individual/index.php?occid=3611988",
    "https://cch2.org/portal/collections/individual/index.php?occid=3611990",
    "https://cch2.org/portal/collections/individual/index.php?occid=3611992",
    "https://cch2.org/portal/collections/individual/index.php?occid=3611993",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612015",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612017",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612018",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612020",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612021",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612022",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612024",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612025",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612026",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612027",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612028",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612033",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612035",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612036",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612202",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612238",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612391",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612398",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612415",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612416",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612417",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612756",
    "https://cch2.org/portal/collections/individual/index.php?occid=3612758",
    "https://cch2.org/portal/collections/individual/index.php?occid=3615443",
    "https://cch2.org/portal/collections/individual/index.php?occid=3617268",
    "https://cch2.org/portal/collections/individual/index.php?occid=3617348",
    "https://cch2.org/portal/collections/individual/index.php?occid=3618225",
    "https://cch2.org/portal/collections/individual/index.php?occid=3618669",
    "https://cch2.org/portal/collections/individual/index.php?occid=3618936",
    "https://cch2.org/portal/collections/individual/index.php?occid=3620050",
    "https://cch2.org/portal/collections/individual/index.php?occid=3621576",
    "https://cch2.org/portal/collections/individual/index.php?occid=3656309",
    "https://cch2.org/portal/collections/individual/index.php?occid=36646",
    "https://cch2.org/portal/collections/individual/index.php?occid=3700295",
    "https://cch2.org/portal/collections/individual/index.php?occid=3700297",
    "https://cch2.org/portal/collections/individual/index.php?occid=3700298",
    "https://cch2.org/portal/collections/individual/index.php?occid=3810276",
    "https://cch2.org/portal/collections/individual/index.php?occid=3810277",
    "https://cch2.org/portal/collections/individual/index.php?occid=3810278",
    "https://cch2.org/portal/collections/individual/index.php?occid=3826742",
    "https://cch2.org/portal/collections/individual/index.php?occid=3826803",
    "https://cch2.org/portal/collections/individual/index.php?occid=3826866",
    "https://cch2.org/portal/collections/individual/index.php?occid=3826872",
    "https://cch2.org/portal/collections/individual/index.php?occid=3826916",
    "https://cch2.org/portal/collections/individual/index.php?occid=3826971",
    "https://cch2.org/portal/collections/individual/index.php?occid=3827001",
    "https://cch2.org/portal/collections/individual/index.php?occid=3827041",
    "https://cch2.org/portal/collections/individual/index.php?occid=3827089",
    "https://cch2.org/portal/collections/individual/index.php?occid=3948469",
    "https://cch2.org/portal/collections/individual/index.php?occid=3948470",
    "https://cch2.org/portal/collections/individual/index.php?occid=3949199",
    "https://cch2.org/portal/collections/individual/index.php?occid=3949203",
    "https://cch2.org/portal/collections/individual/index.php?occid=4068227",
    "https://cch2.org/portal/collections/individual/index.php?occid=4068228",
    "https://cch2.org/portal/collections/individual/index.php?occid=4072307",
    "https://cch2.org/portal/collections/individual/index.php?occid=407313",
    "https://cch2.org/portal/collections/individual/index.php?occid=4074850",
    "https://cch2.org/portal/collections/individual/index.php?occid=4074851",
    "https://cch2.org/portal/collections/individual/index.php?occid=4074852",
    "https://cch2.org/portal/collections/individual/index.php?occid=4075140",
    "https://cch2.org/portal/collections/individual/index.php?occid=4076029",
    "https://cch2.org/portal/collections/individual/index.php?occid=4078612",
    "https://cch2.org/portal/collections/individual/index.php?occid=4083202",
    "https://cch2.org/portal/collections/individual/index.php?occid=4083924",
    "https://cch2.org/portal/collections/individual/index.php?occid=4084012",
    "https://cch2.org/portal/collections/individual/index.php?occid=4084283",
    "https://cch2.org/portal/collections/individual/index.php?occid=4084876",
    "https://cch2.org/portal/collections/individual/index.php?occid=4085847",
    "https://cch2.org/portal/collections/individual/index.php?occid=4085988",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095374",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095375",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095376",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095377",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095378",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095379",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095380",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095381",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095382",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095383",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095384",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095385",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095386",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095387",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095388",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095389",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095390",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095391",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095392",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095393",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095394",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095395",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095396",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095397",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095398",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095399",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095400",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095401",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095402",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095403",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095404",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095405",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095406",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095407",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095408",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095409",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095410",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095411",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095412",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095413",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095414",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095415",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095416",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095417",
    "https://cch2.org/portal/collections/individual/index.php?occid=4095418",
    "https://cch2.org/portal/collections/individual/index.php?occid=4235",
    "https://cch2.org/portal/collections/individual/index.php?occid=42726",
    "https://cch2.org/portal/collections/individual/index.php?occid=4455",
    "https://cch2.org/portal/collections/individual/index.php?occid=4464643",
    "https://cch2.org/portal/collections/individual/index.php?occid=4471937",
    "https://cch2.org/portal/collections/individual/index.php?occid=4474805",
    "https://cch2.org/portal/collections/individual/index.php?occid=45902",
    "https://cch2.org/portal/collections/individual/index.php?occid=4620146",
    "https://cch2.org/portal/collections/individual/index.php?occid=4620471",
    "https://cch2.org/portal/collections/individual/index.php?occid=4621000",
    "https://cch2.org/portal/collections/individual/index.php?occid=468960",
    "https://cch2.org/portal/collections/individual/index.php?occid=468969",
    "https://cch2.org/portal/collections/individual/index.php?occid=468976",
    "https://cch2.org/portal/collections/individual/index.php?occid=468981",
    "https://cch2.org/portal/collections/individual/index.php?occid=468989",
    "https://cch2.org/portal/collections/individual/index.php?occid=468999",
    "https://cch2.org/portal/collections/individual/index.php?occid=469000",
    "https://cch2.org/portal/collections/individual/index.php?occid=469003",
    "https://cch2.org/portal/collections/individual/index.php?occid=469004",
    "https://cch2.org/portal/collections/individual/index.php?occid=469009",
    "https://cch2.org/portal/collections/individual/index.php?occid=469013",
    "https://cch2.org/portal/collections/individual/index.php?occid=469014",
    "https://cch2.org/portal/collections/individual/index.php?occid=469016",
    "https://cch2.org/portal/collections/individual/index.php?occid=469017",
    "https://cch2.org/portal/collections/individual/index.php?occid=469020",
    "https://cch2.org/portal/collections/individual/index.php?occid=469022",
    "https://cch2.org/portal/collections/individual/index.php?occid=469023",
    "https://cch2.org/portal/collections/individual/index.php?occid=469024",
    "https://cch2.org/portal/collections/individual/index.php?occid=469030",
    "https://cch2.org/portal/collections/individual/index.php?occid=469034",
    "https://cch2.org/portal/collections/individual/index.php?occid=469035",
    "https://cch2.org/portal/collections/individual/index.php?occid=469037",
    "https://cch2.org/portal/collections/individual/index.php?occid=469039",
    "https://cch2.org/portal/collections/individual/index.php?occid=469041",
    "https://cch2.org/portal/collections/individual/index.php?occid=469042",
    "https://cch2.org/portal/collections/individual/index.php?occid=469044",
    "https://cch2.org/portal/collections/individual/index.php?occid=469045",
    "https://cch2.org/portal/collections/individual/index.php?occid=469047",
    "https://cch2.org/portal/collections/individual/index.php?occid=469048",
    "https://cch2.org/portal/collections/individual/index.php?occid=469049",
    "https://cch2.org/portal/collections/individual/index.php?occid=469050",
    "https://cch2.org/portal/collections/individual/index.php?occid=469051",
    "https://cch2.org/portal/collections/individual/index.php?occid=469052",
    "https://cch2.org/portal/collections/individual/index.php?occid=469056",
    "https://cch2.org/portal/collections/individual/index.php?occid=469057",
    "https://cch2.org/portal/collections/individual/index.php?occid=469059",
    "https://cch2.org/portal/collections/individual/index.php?occid=469060",
    "https://cch2.org/portal/collections/individual/index.php?occid=469068",
    "https://cch2.org/portal/collections/individual/index.php?occid=469070",
    "https://cch2.org/portal/collections/individual/index.php?occid=469071",
    "https://cch2.org/portal/collections/individual/index.php?occid=469075",
    "https://cch2.org/portal/collections/individual/index.php?occid=469076",
    "https://cch2.org/portal/collections/individual/index.php?occid=469077",
    "https://cch2.org/portal/collections/individual/index.php?occid=469080",
    "https://cch2.org/portal/collections/individual/index.php?occid=469081",
    "https://cch2.org/portal/collections/individual/index.php?occid=469082",
    "https://cch2.org/portal/collections/individual/index.php?occid=469083",
    "https://cch2.org/portal/collections/individual/index.php?occid=469084",
    "https://cch2.org/portal/collections/individual/index.php?occid=469086",
    "https://cch2.org/portal/collections/individual/index.php?occid=469087",
    "https://cch2.org/portal/collections/individual/index.php?occid=469088",
    "https://cch2.org/portal/collections/individual/index.php?occid=469089",
    "https://cch2.org/portal/collections/individual/index.php?occid=469092",
    "https://cch2.org/portal/collections/individual/index.php?occid=469093",
    "https://cch2.org/portal/collections/individual/index.php?occid=469094",
    "https://cch2.org/portal/collections/individual/index.php?occid=469097",
    "https://cch2.org/portal/collections/individual/index.php?occid=469098",
    "https://cch2.org/portal/collections/individual/index.php?occid=469099",
    "https://cch2.org/portal/collections/individual/index.php?occid=469100",
    "https://cch2.org/portal/collections/individual/index.php?occid=469101",
    "https://cch2.org/portal/collections/individual/index.php?occid=469102",
    "https://cch2.org/portal/collections/individual/index.php?occid=469103",
    "https://cch2.org/portal/collections/individual/index.php?occid=469104",
    "https://cch2.org/portal/collections/individual/index.php?occid=469108",
    "https://cch2.org/portal/collections/individual/index.php?occid=469109",
    "https://cch2.org/portal/collections/individual/index.php?occid=469112",
    "https://cch2.org/portal/collections/individual/index.php?occid=469116",
    "https://cch2.org/portal/collections/individual/index.php?occid=469117",
    "https://cch2.org/portal/collections/individual/index.php?occid=469118",
    "https://cch2.org/portal/collections/individual/index.php?occid=469120",
    "https://cch2.org/portal/collections/individual/index.php?occid=469124",
    "https://cch2.org/portal/collections/individual/index.php?occid=469127",
    "https://cch2.org/portal/collections/individual/index.php?occid=469130",
    "https://cch2.org/portal/collections/individual/index.php?occid=469131",
    "https://cch2.org/portal/collections/individual/index.php?occid=469132",
    "https://cch2.org/portal/collections/individual/index.php?occid=469133",
    "https://cch2.org/portal/collections/individual/index.php?occid=469141",
    "https://cch2.org/portal/collections/individual/index.php?occid=469142",
    "https://cch2.org/portal/collections/individual/index.php?occid=469143",
    "https://cch2.org/portal/collections/individual/index.php?occid=469144",
    "https://cch2.org/portal/collections/individual/index.php?occid=469145",
    "https://cch2.org/portal/collections/individual/index.php?occid=469146",
    "https://cch2.org/portal/collections/individual/index.php?occid=469150",
    "https://cch2.org/portal/collections/individual/index.php?occid=469153",
    "https://cch2.org/portal/collections/individual/index.php?occid=469154",
    "https://cch2.org/portal/collections/individual/index.php?occid=469156",
    "https://cch2.org/portal/collections/individual/index.php?occid=469159",
    "https://cch2.org/portal/collections/individual/index.php?occid=469161",
    "https://cch2.org/portal/collections/individual/index.php?occid=469162",
    "https://cch2.org/portal/collections/individual/index.php?occid=469166",
    "https://cch2.org/portal/collections/individual/index.php?occid=469167",
    "https://cch2.org/portal/collections/individual/index.php?occid=469168",
    "https://cch2.org/portal/collections/individual/index.php?occid=469169",
    "https://cch2.org/portal/collections/individual/index.php?occid=469170",
    "https://cch2.org/portal/collections/individual/index.php?occid=469171",
    "https://cch2.org/portal/collections/individual/index.php?occid=469172",
    "https://cch2.org/portal/collections/individual/index.php?occid=469177",
    "https://cch2.org/portal/collections/individual/index.php?occid=469178",
    "https://cch2.org/portal/collections/individual/index.php?occid=469179",
    "https://cch2.org/portal/collections/individual/index.php?occid=4721",
    "https://cch2.org/portal/collections/individual/index.php?occid=49117",
    "https://cch2.org/portal/collections/individual/index.php?occid=51145",
    "https://cch2.org/portal/collections/individual/index.php?occid=52482",
    "https://cch2.org/portal/collections/individual/index.php?occid=55059",
    "https://cch2.org/portal/collections/individual/index.php?occid=5533146",
    "https://cch2.org/portal/collections/individual/index.php?occid=55592",
    "https://cch2.org/portal/collections/individual/index.php?occid=5561921",
    "https://cch2.org/portal/collections/individual/index.php?occid=5563117",
    "https://cch2.org/portal/collections/individual/index.php?occid=5732610",
    "https://cch2.org/portal/collections/individual/index.php?occid=57675",
    "https://cch2.org/portal/collections/individual/index.php?occid=6008207",
    "https://cch2.org/portal/collections/individual/index.php?occid=6017874",
    "https://cch2.org/portal/collections/individual/index.php?occid=6026918",
    "https://cch2.org/portal/collections/individual/index.php?occid=6026919",
    "https://cch2.org/portal/collections/individual/index.php?occid=6048990",
    "https://cch2.org/portal/collections/individual/index.php?occid=61217",
    "https://cch2.org/portal/collections/individual/index.php?occid=631781",
    "https://cch2.org/portal/collections/individual/index.php?occid=632033",
    "https://cch2.org/portal/collections/individual/index.php?occid=645142",
    "https://cch2.org/portal/collections/individual/index.php?occid=648549",
    "https://cch2.org/portal/collections/individual/index.php?occid=652363",
    "https://cch2.org/portal/collections/individual/index.php?occid=667072",
    "https://cch2.org/portal/collections/individual/index.php?occid=668312",
    "https://cch2.org/portal/collections/individual/index.php?occid=6779828",
    "https://cch2.org/portal/collections/individual/index.php?occid=6795972",
    "https://cch2.org/portal/collections/individual/index.php?occid=682744",
    "https://cch2.org/portal/collections/individual/index.php?occid=684007",
    "https://cch2.org/portal/collections/individual/index.php?occid=6851620",
    "https://cch2.org/portal/collections/individual/index.php?occid=6856684",
    "https://cch2.org/portal/collections/individual/index.php?occid=6856685",
    "https://cch2.org/portal/collections/individual/index.php?occid=698690",
    "https://cch2.org/portal/collections/individual/index.php?occid=705793",
    "https://cch2.org/portal/collections/individual/index.php?occid=710528",
    "https://cch2.org/portal/collections/individual/index.php?occid=712539",
    "https://cch2.org/portal/collections/individual/index.php?occid=712565",
    "https://cch2.org/portal/collections/individual/index.php?occid=715148",
    "https://cch2.org/portal/collections/individual/index.php?occid=734125",
    "https://cch2.org/portal/collections/individual/index.php?occid=753633",
    "https://cch2.org/portal/collections/individual/index.php?occid=764500",
    "https://cch2.org/portal/collections/individual/index.php?occid=765477",
    "https://cch2.org/portal/collections/individual/index.php?occid=79706",
    "https://cch2.org/portal/collections/individual/index.php?occid=806147",
    "https://cch2.org/portal/collections/individual/index.php?occid=81912",
    "https://cch2.org/portal/collections/individual/index.php?occid=824961",
    "https://cch2.org/portal/collections/individual/index.php?occid=83203",
    "https://cch2.org/portal/collections/individual/index.php?occid=863673",
    "https://cch2.org/portal/collections/individual/index.php?occid=87291",
    "https://cch2.org/portal/collections/individual/index.php?occid=884527",
    "https://cch2.org/portal/collections/individual/index.php?occid=89884",
    "https://cch2.org/portal/collections/individual/index.php?occid=899090",
    "https://cch2.org/portal/collections/individual/index.php?occid=902357",
    "https://cch2.org/portal/collections/individual/index.php?occid=906238",
    "https://cch2.org/portal/collections/individual/index.php?occid=911273",
    "https://cch2.org/portal/collections/individual/index.php?occid=911854",
    "https://cch2.org/portal/collections/individual/index.php?occid=91393",
    "https://cch2.org/portal/collections/individual/index.php?occid=920878",
    "https://cch2.org/portal/collections/individual/index.php?occid=92110",
    "https://cch2.org/portal/collections/individual/index.php?occid=929206",
    "https://cch2.org/portal/collections/individual/index.php?occid=929536",
    "https://cch2.org/portal/collections/individual/index.php?occid=935273",
    "https://cch2.org/portal/collections/individual/index.php?occid=936997",
    "https://cch2.org/portal/collections/individual/index.php?occid=942849",
    "https://cch2.org/portal/collections/individual/index.php?occid=947300",
    "https://cch2.org/portal/collections/individual/index.php?occid=95043",
    "https://cch2.org/portal/collections/individual/index.php?occid=957317",
    "https://cch2.org/portal/collections/individual/index.php?occid=96130",
    "https://cch2.org/portal/collections/individual/index.php?occid=963330",
    "https://cch2.org/portal/collections/individual/index.php?occid=970742",
    "https://cch2.org/portal/collections/individual/index.php?occid=971402",
    "https://cch2.org/portal/collections/individual/index.php?occid=977847",
    "https://cch2.org/portal/collections/individual/index.php?occid=978519",
    "https://cch2.org/portal/collections/individual/index.php?occid=979589",
    "https://cch2.org/portal/collections/individual/index.php?occid=981549",
]

SESSION = requests.Session()
SESSION.headers.update({
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
})

def check_url(url):
    occid = url.split('occid=')[1]
    try:
        resp = SESSION.get(url, timeout=15)
        resp.raise_for_status()
        html = resp.text

        # Pages WITH an image always contain "Specimen Media" as a section heading
        # AND hyperlinks labeled "Open Medium File" and/or "Open Large File".
        # Pages WITHOUT an image contain neither of these strings.
        has_specimen_media = 'Specimen Media' in html
        has_file_links = ('Open Medium File' in html) or ('Open Large File' in html)

        if has_specimen_media and has_file_links:
            return (url, occid, "Image present")
        else:
            return (url, occid, "No image")

    except Exception as e:
        return (url, occid, f"Error: {e}")


def main():
    results = {}
    completed = 0
    total = len(URLS)

    # Use 5 threads — polite but fast
    with ThreadPoolExecutor(max_workers=5) as executor:
        futures = {executor.submit(check_url, url): url for url in URLS}
        for future in as_completed(futures):
            url, occid, result = future.result()
            results[url] = (occid, result)
            completed += 1
            if completed % 25 == 0:
                print(f"  Progress: {completed}/{total}")
            # Small polite delay
            time.sleep(0.05)

    # Write CSV in original URL order
    output_file = "cch2_image_results.csv"
    with open(output_file, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["url", "occid", "has_image"])
        for url in URLS:
            occid, result = results[url]
            writer.writerow([url, occid, result])

    print(f"\nDone! Results saved to {output_file}")

    # Also print in order
    print("\n--- Results in original order ---")
    for url in URLS:
        occid, result = results[url]
        print(f"occid={occid}: {result}")


if __name__ == "__main__":
    main()
